apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: itext-dito
  name: itext-dito
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: itext-dito
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: itext-dito
      namespace: default
    spec:
      automountServiceAccountToken: false
      containers:
      - name: itext-dito
        image: itext/dito-sdk:1.3.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DITO_LICENSE_FILE
          value: dito_trial_HMRC.xml
        volumeMounts:
          - name: config-volume
            mountPath: /etc/opt/dito/shared
          - name: work-volume
            mountPath: /var/opt/dito
          - name: log-volume
            mountPath: /var/log/dito
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 12
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 200Mi
      volumes:
        - name: config-volume
          configMap:
            name: licence-config
        - name: work-volume
          emptyDir: {}
        - name: log-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
