apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: itext-dito
  name: itext-dito
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: itext-dito
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: itext-dito
      namespace: default
    spec:
      automountServiceAccountToken: false
      containers:
      - name: itext-dito
        image: itext/dito-sdk:1.3.6
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DITO_LICENSE_FILE
          value: dito_trial_HMRC.xml
        volumeMounts:
          - name: config-volume
            mountPath: /etc/opt/dito/shared
          - name: work-volume
            mountPath: /var/opt/dito
          - name: log-volume
            mountPath: /var/log/dito
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/status
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 12
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 200Mi
      initContainers:
      - name: copy
        image: itext/dito-sdk:1.3.6
        command: ["bash", "-c", "cp /var/tmp/dito/NRS_PDF.dito /var/opt/dito/NRS_PDF.dito"]
        volumeMounts:
          - name: template-volume
            mountPath: /var/tmp/dito
          - name: work-volume
            mountPath: /var/opt/dito
      volumes:
        - name: config-volume
          configMap:
            name: licence-config
        - name: template-volume
          configMap:
            name: template-config
        - name: log-volume
          emptyDir: {}
        - name: work-volume
          emptyDir: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: itext-dito
  name: itext-dito
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: itext-dito
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-next-upstream: error timeout http_502 http_503 http_504
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "0"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: itext-dito
  namespace: default
spec:
  rules:
    - host: services.qa.nrs
      http:
        paths:
          - backend:
              serviceName: itext-dito
              servicePort: 8080
            path: /api
  tls:
    - hosts:
        - services.qa.nrs
      secretName: nginx-ingress-cert